export enum BlockType {
    Empty = 0,
    Two = 2,
    Four = 4,
    Eight = 8,
    Sixteen = 16,
    ThirtyTwo = 32,
    SixtyFour = 64,
    OneHundredTwentyEight = 128,
    TwoHundredFiftySix = 256,
    FiveHundredTwelve = 512,
    OneThousandTwentyFour = 1024,
    TwoThousandFortyEight = 2048,
    FourThousandNinetySix = 4096,
    EightThousandOneHundredNinetyTwo = 8192,
    SixteenThousandTreeHundredEightyFour = 16384,
}